### ISSUE TITLE
may lose some events

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#114]
https://github.com/darwinia-network/bridger/blob/a4b351af7cb250a1f7b2efa34baa2c3ec66a97bf/src/service/subscribe/mod.rs#L84

if some error occurs here, we may lose events in this block since the next block index still moves forward.

**Comment by wuminzhe** [comment]
Yes, it will move forward. If found errors, you can `set-darwinia-start` back to redo previous events.
Maybe we can take different handling methods according to different errors

**Comment by xiaoch05** [comment]
if we use `set-darwinia-start` to go back to the error block
then the bridger will redo the blocks higher than that error block which we have been processed.
Yes, using different methods according to different errors is a good idea, we should retry when it's network error.

**Comment by wuminzhe** [comment]
So we need to consider preventing repeated execution of the events handling.

**Comment by HackFisher** [comment]
Duplicated with #168
