### ISSUE TITLE
we should use a security way to save user's private key

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#140]
right now we have many private keys save in the configure file, it's not safe.
we may use some other ways such as key-store or other crypto ways to save them.

**Comment by HackFisher** [comment]
There was an handy cmd tool in old bridger implementation:

https://github.com/darwinia-network/bridger/blob/fd1c67bacafd42f0e350653e45a162aeeb57218a/provider/darwinia-bridger/src/cmd/encrypt_key.rs#L11

We might need to move it or reimplement it in new bridger implementation.

**Comment by fewensa** [comment]
It's solved by this commit  https://github.com/darwinia-network/bridger/pull/203/commits/263354e297481757fffc505b74b6518da2784951.

For examples.

```rust
#[derive(BridgeCrypto)]
pub struct Foo {
    #[crypto(is_enable)]
    enable: bool,
    #[crypto(decrypt)]
    name: String,
    #[crypto(decrypt)]
    country: String,
    power_level: u64,
}
```

this will be expand

```rust
pub struct Foo {
    #[crypto(is_enable)]
    enable: bool,
    #[crypto(decrypt)]
    name: String,
    #[crypto(decrypt)]
    country: String,
    #[crypto(decrypt)]
    power_level: u64,
}
impl Foo {
    pub fn name_decrypt(&self, password: impl AsRef<str>) -> anyhow::Result<String> {
        if !self.enable {
            return Ok(self.name.clone());
        }
        let crypto = bridge_primitives::crypto::Crypto::new();
        crypto.decrypt(password.as_ref(), &self.name)
    }
    pub fn country_decrypt(&self, password: impl AsRef<str>) -> anyhow::Result<String> {
        if !self.enable {
            return Ok(self.country.clone());
        }
        let crypto = bridge_primitives::crypto::Crypto::new();
        crypto.decrypt(password.as_ref(), &self.country)
    }
}
```

The [`bridge-primitives`](https://github.com/darwinia-network/bridger/blob/fd1c67bacafd42f0e350653e45a162aeeb57218a/primitives/Cargo.toml#L2) crate is required.

Use it.

```rust
let foo = Foo { .. }
let name = foo.name_decrypt("password").except("failed to decrypt name");
```
