### ISSUE TITLE
why we don't need to check if the account use proxy?

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#151]
https://github.com/darwinia-network/bridger/blob/4be9a8da2bf2af2d9455eedf60dd09a1aa0bf979/src/api/darwinia_sender.rs#L185
also for line 200
https://github.com/darwinia-network/bridger/blob/master/src/api/darwinia_sender.rs#L200

**Comment by wuminzhe** [comment]
proxy has no right to sign. it is authority's right. the authority account is the 'real'

**Comment by xiaoch05** [comment]
Yes, so the authority is not `self.account_id` but real if the account uses proxy. Then in this situation, we should check real?

**Comment by wuminzhe** [comment]
you are right, this should be changed to `real` if `real` exists.
