### ISSUE TITLE
bridger should not ignore the affirmed block

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#154]
[2021-02-01T13:03:04Z TRACE darwinia_bridger::service::subscribe] >> Event - EthereumRelay::Affirmed

[2021-02-01T13:03:27Z INFO  darwinia_bridger::service::extrinsics] Affirmed ethereum block 9578895 in extrinsic 0x6ded1200c2e7cf49891c7e1581a7e8c4ce80baf0a5aba689897d660a2487722c

bridger found affirmed block 9578895 by Event EthereumRelay::Affirmed which created by extrinsic
https://crab.subscan.io/extrinsic/0x06e26aba1a3b2218e859a611ffecca93128d080f230460505708e501c4025658

but it ignored and also create a failed extrinsic
https://crab.subscan.io/extrinsic/0x6ded1200c2e7cf49891c7e1581a7e8c4ce80baf0a5aba689897d660a2487722c

**Comment by wuminzhe** [comment]
relate to #24

**Comment by HackFisher** [comment]
The fundamental solution for this would be validate signed in extrinsic pool in nodes & network side, because the affirm can still failed if there are no events, two affirm goes into extrinsic pool at the same time.

https://github.com/darwinia-network/darwinia-common/issues/669
