### ISSUE TITLE
duplicate scan block number

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#158]
https://github.com/darwinia-network/bridger/blob/20a5a3acdbc71845be8a8b425ac0d55c865c4a9b/src/service/ethereum.rs#L97

scan_from should be latest_block_number+1

**Comment by HackFisher** [comment]
@wuminzhe Has this already been fixed in latest code?

**Comment by HackFisher** [comment]
@xiaoch05 Please help check wether this issue still exists, and please help fix it if yes.

**Comment by xiaoch05** [comment]
this has been solved. See https://github.com/darwinia-network/bridger/blob/master/supports/evm-log-tracker/src/evm_log_tracker.rs#L76
