### ISSUE TITLE
wrong sign_mmr_root status

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#159]
https://github.com/darwinia-network/bridger/blob/20a5a3acdbc71845be8a8b425ac0d55c865c4a9b/src/service/subscribe/mod.rs#L139

at block `header.number`, we may get the wrong status of the sign_mmr_root with a high probability, and then send extrinsic with error result. Instead, it may be better to use the latest block by `None` here.

**Comment by wuminzhe** [comment]
Why get the wrong status with a high probability?

**Comment by xiaoch05** [comment]
have not caught the deep reason, I tried to remove the `header.number`, and it got the right status.
I think the `header.number` is a critical point of the status change.

**Comment by wuminzhe** [comment]
if using `None` here, the result is not the result in that moment.

**Comment by xiaoch05** [comment]
do we need the latest result or the result at that moment here? 
If the mmr root has been signed by all other authorities after that block. we should not sign again.

**Comment by wuminzhe** [comment]
I forget why this is added here. The original method is what you said, I will think about it.
