### ISSUE TITLE
lose event if bridger can't decode all of the events in the block.

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#168]
Suppose bridger needs `EventA`, and it can decode the event.

But someday another event `EventB` is deposited with `EventA` at the same block. And bridger cannot decode it.

Then it will also ignore `EventA`.

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/issues/9480

**Comment by HackFisher** [comment]
Related https://github.com/darwinia-network/bridger/issues/180

**Comment by HackFisher** [comment]
Will be fixed after Metadata V14(Subquery Supoort) and #303

**Comment by fewensa** [comment]
Close it, follow #303
