### ISSUE TITLE
unknown field `justifications`, cannot get block from pangolin using current subxt?

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#171]
With the latest darwinia-common's master branch(https://github.com/darwinia-network/darwinia-common/commit/77453420acbc04218c378df534d31d0fa2f4959a), the bridger gets the following error when using subxt to get block by block_hash.
Maybe the substrate used by darwinia-common is incompatible with subxt.
```
[2021-03-29T01:07:25Z ERROR darwinia_bridger::service::subscribe::darwinia_tracker] An error occurred while tracking next darwinia block: SubxtError(
        Rpc(
            ParseError(
                Error("unknown field `justifications`, expected `block` or `justification`", line: 0, column: 0),
            ),
        ),
    )
```

**Comment by wuminzhe** [comment]
pangolin or darwinia mainnet?

**Comment by xiaoch05** [comment]
> pangolin or darwinia mainnet?

pangolin

**Comment by wuminzhe** [comment]
SignedBlock uses `justification`，but pangolin's chain_getBlock return `justifications`

**Comment by wuminzhe** [comment]
Wait for subxt updateing

**Comment by HackFisher** [comment]
Related https://github.com/darwinia-network/bridger/issues/185

**Comment by fewensa** [comment]
Close it, talk in #185
