### ISSUE TITLE
Darwinia BSC Bridge Task

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/bridger#175]
clique, aura, heco, bsc.

### `Backing Contract` on PoA chain

storage: [who(from) locked how many(amount) what(erc20) tokens]

### `Issuing Pallet` on Darwinia

- verify messages
- issue mapped tokens

### `PoA Light Client Pallet` on Darwinia

- verify PoA headers and their finality.
- store PoA headers

https://github.com/paritytech/parity-bridges-common/tree/master/modules/ethereum

Something to change: 
1. The `import header` call should be changed to support forking because clique allows multiple authorities to generate blocks during a block generation period
2. The fork is solved by comparing the accumulated difficulty
3. A block must wait for 1/2*N+1 confirmations before being finalized

https://docs.binance.org/smart-chain/guides/concepts/consensus.html
https://docs.hecochain.com/#/consensus

### `Relayer`

* PoA > Darwinia
  - relay blocks
  - subscribe lock event
  - determine whether it need to relay the the lock related message to Darwinia
      1. check the latest block's storage
      2. check the status of the message on Darwinia
  - relay the lock related message to Darwinia

* ACK message (Darwinia > PoA)
  - relay the issue event proof to PoA chain.

**Comment by wuminzhe** [comment]
https://github.com/darwinia-network/darwinia/issues/656

**Comment by fewensa** [comment]
Use new solutions. https://github.com/darwinia-network/darwinia/issues/753
