### ISSUE TITLE
Bridger does not auto restart on system(CodeUpdated)

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#180]
```
[2021-05-13T08:37:11Z ERROR darwinia_bridger::tools] Rpc error: JSON-RPC request error: Error { code: MethodError(1010), message: "Invalid Transaction", data: Some(String("Transaction has a bad signature")) }
    Caused by:
        0: JSON-RPC request error: Error { code: MethodError(1010), message: "Invalid Transaction", data: Some(String("Transaction has a bad signature")) }
        1: Method error: Invalid Transaction
[2021-05-13T08:37:13Z ERROR darwinia_bridger::tools] Rpc error: JSON-RPC request error: Error { code: MethodError(1010), message: "Invalid Transaction", data: Some(String("Transaction has a bad signature")) }
    Caused by:
        0: JSON-RPC request error: Error { code: MethodError(1010), message: "Invalid Transaction", data: Some(String("Transaction has a bad signature")) }
        1: Method error: Invalid Transaction
```

Might related to some other failure of decode event? cause middle exit before decode system(CodeUpdated)

**Comment by wuminzhe** [comment]
bridger encountered an event that has an unknown type. Unfortunately, the `CodeUpdated` event is in the same block.

**Comment by wuminzhe** [comment]
If we want to completely solve this problem, we must define all possible types or the length of all types.

**Comment by wuminzhe** [comment]
> If we want to completely solve this problem, we must define all possible types or the length of all types.

We can not know the length of all types before we meet the data. For example, Vec<...>, the length of this type is different in different vec length. The vec length is a Compact type.

**Comment by AurevoirXavier** [comment]
There's another way, subscribe storage `System::LastRuntimeUpgrade`.

**Comment by wuminzhe** [comment]
> There's another way, subscribe storage `System::LastRuntimeUpgrade`.

Good idea. We can subscribe the changes of the storages we care.
