### ISSUE TITLE
Check substrate-subxt after upgrading its substrate dependency

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#185]
https://github.com/darwinia-network/substrate-subxt/commit/2e763e13df054417a7661b4afad73b2c40eb5bfd

**Comment by HackFisher** [comment]
This changes in https://github.com/darwinia-network/bridger/blob/fd1c67bacafd42f0e350653e45a162aeeb57218a/provider/darwinia-bridger/src/cmd/encrypt_key.rs#L11

and https://github.com/darwinia-network/substrate-subxt

might need to revert when substrate-subxt and darwinia's substrate dep get upgraded.

**Comment by xiaoch05** [comment]
if substrate is upgraded for subxt, we should revert this modification.

**Comment by fewensa** [comment]
The version [darwinia-v0.11.6](https://github.com/darwinia-network/substrate/releases/tag/darwinia-v0.11.6) is same with this modification 

https://github.com/darwinia-network/substrate/blob/74101dc21cfffb4c2d014fcc28edc166d5ca1b16/primitives/runtime/src/lib.rs#L105-L109

https://github.com/darwinia-network/substrate-subxt/commit/2e763e13df054417a7661b4afad73b2c40eb5bfd

So there remove by [subxt@darwinia-v0.11.6](https://github.com/darwinia-network/substrate-subxt/releases/tag/darwinia-v0.11.6)

https://github.com/darwinia-network/substrate-subxt/commit/d63ee2c1715e6f469193ecaad54e89f97022035f#diff-5cdcc3261dd77eadb37bcd60c5f85affcc9306454ae7bb8128e6d096ae51a631L89
