### ISSUE TITLE
we always get the ws error when affirm ethereum block

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#211]
[2021-07-28T05:53:03Z ERROR task_pangolin_ropsten::service::relay] affirm err: SubxtError(
        Rpc(
            RestartNeeded(
                "Networking or low-level protocol error: error in the WebSocket connection",
            ),
        ),
    )

the rpc URL:
wss://pangolin-rpc.darwinia.network

**Comment by wuminzhe** [comment]
应该是你网络不好，我开始的时候也这样，会重来

**Comment by AurevoirXavier** [comment]
Try `t2.pangolin-p2p.darwinia.network`?

**Comment by HackFisher** [comment]
需要根据Error类型，进行分类异常处理
