### ISSUE TITLE
[ethereum>darwinia]Checking existing pending/affirmed headers status before affirm.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#24]
- [ ] Check https://github.com/darwinia-network/bridger/issues/154

**Comment by wuminzhe** [comment]
https://github.com/darwinia-network/bridger/blob/7463ceb1c0a897fe68c5a106631e0063773bd62b/src/api/darwinia.rs#L236

**Comment by HackFisher** [comment]
- [ ] Remove ```confirmed_blocks.contains(&target)```
- [ ] If there is pending header that I agree and large than my target, I should not relay
- [ ] If there is pending header that I didn't agree, should print warning log and report to technical committee queue or action if I'm technical member.
- [ ] Round 0 affirmations checking, If there is round-0 affirmation that I agree and larger than my target, I should join the game or do not relay.
- [ ] Round 0 affirmations checking, If there is round-0 affirmation that I disagree and larger than my target, I should join the game by ```dispute_and_affirm``` or following existing agreed ```disputed_affirmations```.
- [ ] Round 0 affirmations checking, if the current round is not 0, and my target is less than the ```game_id``` (block_number), I should join the game.

**Comment by HackFisher** [comment]
Q: How to check whether I agree or not?
A: Compare the ```header_hash``` and ```mmr_root``` in the ```HeaderParcel```, from my honest(trusted) shadow service and from honest darwinia nodes.

**Comment by wuminzhe** [comment]
```ruby
games = {
  game_id: {
    round_id: [
      affirmation1,
      affirmation2,
      ...
    ]
  }
}

games.each_pair do |game_id, rounds|
  rounds.each_pair do |round_id, affirmations|
    if round_id == 0
      if large_block_exists(affirmations, target)
        if agree(affirmations, target)
          join_game(game_id, target) # or do not relay
        else # disagree
          dispute_and_affirm(game_id, target) # or following existing agreed disputed_affirmations
        end
      end
    else
      if target <= game_id
        join_game(game_id, target)
      end
    end
  end
end
```

**Comment by fewensa** [comment]
This problem should not exist after using thegraph, right?  @HackFisher

**Comment by HackFisher** [comment]
> This problem should not exist after using thegraph, right? @HackFisher

No, let's keep it as it is, it is another topic for further checking affirms.

**Comment by HackFisher** [comment]
Will deprecate and won't fix
