### ISSUE TITLE
bridger don't retry to send redeem tx after mmr root confirmed

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#243]
[log.txt](https://github.com/darwinia-network/bridger/files/6989239/log.txt)

**Comment by HackFisher** [comment]
Related with #249 ?

**Comment by xiaoch05** [comment]
> Related with #249 ?

yes

**Comment by HackFisher** [comment]
@xiaoch05 Was this fixed by #249 ? If yes, please close it in related pull request?

**Comment by xiaoch05** [comment]
solved by #249
