### ISSUE TITLE
should give up some invalid redeem transaction

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/bridger#258]
If some redeem transaction always failed(which means the transition is sent successfully but the execution result on chain is failed). Then bridger should not try to send it again and again. It should give up when tried many times to save relay fees.

**Comment by HackFisher** [comment]
There are two cases under the new model:

1. The message is not successfully sent. This should be checked, might due to protocol error or bridger software bugs.
2. The message is sent & dispatched but failed, it is normal.

Simple do retry require a reason, connections stability? Other wise, it will not help in anyway.


@xiaoch05 Please help provide a permlink to the code line, which can help others get started.

**Comment by xiaoch05** [comment]
> There are two cases under the new model:
> 
> 1. The message is not successfully sent. This should be checked, might due to protocol error or bridger software bugs.
> 2. The message is sent & dispatched but failed, it is normal.
> 
> Simple do retry require a reason, connections stability? Other wise, it will not help in anyway.
> 
> @xiaoch05 Please help provide a permlink to the code line, which can help others get started.

Exactly, right now we have not solved model 2 well.

https://github.com/darwinia-network/bridger/blob/master/task/task-pangolin-ropsten/src/service/ropsten/ropsten_logs_handler.rs#L177-L186

currently, we have no problem before restart. Because once a transaction is sent successfully, we will not send it again. But if there are some bugs in the source chain or shadow. We get the wrong data, and this data will never be verified. Then the bridge will always check the redeem confirmation. And when restart, it will send the redeem transaction with the wrong data again.

**Comment by HackFisher** [comment]
When a extrinsic/transaction fails, we need to print error logs for diagnostic, or collect to metrics such as Prometheus?

**Comment by xiaoch05** [comment]
> When an extrinsic/transaction fails, we need to print error logs for diagnostic, or collect to metrics such as Prometheus?

Should alarm a warning, or collect to metrics to be known by Ops at the first time I think.

**Comment by fewensa** [comment]
The next release version will not have this problem. we just send it without retrying, retry only when the connection is lost, the max times is 11.
https://github.com/darwinia-network/bridger/blob/b150f345331f69808b29a2f326720d451efc5c59/task/task-pangolin-ropsten/src/service/redeem/mod.rs#L177

**Comment by fewensa** [comment]
When all attempts fail, we should log this error, which will be implemented in the future. #316
