### ISSUE TITLE
Wrong version for darwinia

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/bridger#259]
https://github.com/darwinia-network/bridger/blob/1373a4eaa3ed61d0b996eee505d4d6a25468f739/components/client-darwinia-subxt/Cargo.toml#L41-L43

Currently darwinia should use darwinia-v0.11.3  tag

https://github.com/darwinia-network/substrate/tree/darwinia-v0.11.3

https://github.com/darwinia-network/darwinia-common/tree/darwinia-v0.11.3

**Comment by AurevoirXavier** [comment]
Darwinia will not anchor on 0.11.3 tag. Cause we need to apply the companion from common/frontier/bridges-common immediately.

**Comment by fewensa** [comment]
yes

**Comment by AurevoirXavier** [comment]
Okay. Then go v0.11.3
