### ISSUE TITLE
Auto reduce collateral on slash for relayer fee market

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#310]
This is a smart feature can be supported in bridger, it is possible to add this smart feature in on-chain protocol, but for the purpose of simcity, I prefer to add it off-chain.

**Comment by fewensa** [comment]
Yes, So I think we can stop updating the conversion rate.

https://github.com/darwinia-network/bridger/blob/501167e212fc86e19a4e4d8cc1b20e3d18b76ad9/task/task-pangolin-pangoro/src/service/relay.rs?#L159-L190

https://github.com/darwinia-network/bridger/blob/501167e212fc86e19a4e4d8cc1b20e3d18b76ad9/task/task-pangolin-pangoro/src/service/relay.rs#L192-L223

**Comment by fewensa** [comment]
This issue needs to be reimplemented in the refactored s2s bridge.
