### ISSUE TITLE
Upgrade guide for version v0.4.8 or later

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/bridger#315]
For all bridgers.

After #308 and #314 are merged, We planned to publish a new release bridger, the version is v0.4.8, In this version. we have some changes.

- The ethereum/ropsten scanner change use thgraph.
- The pangolin-pangoro bridge uses fee market strategy

And have some data migration. So, you can read this document to know how to upgrade to the new version.

All versions after 0.4.0 will be automatically migrated. You need to check whether the data is correct after migration and update your config file.

- darwinia-ethereum

```bash
bridger kv -n task-darwinia-ethereum get \
  -o table \
  --include-key \
  scan.darwinia.running \
  scan.darwinia.current \
  scan.ethereum.affirm.running \
  scan.ethereum.affirm.current \
  scan.ethereum.redeem.running \
  scan.ethereum.redeem.current \
  scan.ethereum.check.running \
  scan.ethereum.check.current
```

- pangolin-ropsten

```bash
bridger kv -n task-pangolin-ropsten get \
  -o table \
  --include-key \
  scan.pangolin.running \
  scan.pangolin.current \
  scan.ropsten.affirm.running \
  scan.ropsten.affirm.current \
  scan.ropsten.redeem.running \
  scan.ropsten.redeem.current \
  scan.ropsten.check.running \
  scan.ropsten.check.current
```

If it is normal, you will see output similar to the following 

```
+-----------------------------+----------+
| scan.pangolin.running       | true     |
+-----------------------------+----------+
| scan.pangolin.current       | 1407316  |
+-----------------------------+----------+
| scan.ropsten.affirm.running | true     |
+-----------------------------+----------+
| scan.ropsten.affirm.current | 11454065 |
+-----------------------------+----------+
| scan.ropsten.redeem.running | true     |
+-----------------------------+----------+
| scan.ropsten.redeem.current | 11454065 |
+-----------------------------+----------+
| scan.ropsten.check.running  | true     |
+-----------------------------+----------+
| scan.ropsten.check.current  | 11453643 |
+-----------------------------+----------+
```

You can also control whether to run 

```
bridger kv -n task-darwinia-ethereum put scan.darwinia.running false
```

and run from a special block number

```
bridger kv -n task-darwinia-ethereum put scan.darwinia.planned 123456
```

```
bridger kv -n task-darwinia-ethereum put scan.ethereum.redeem.planned 123456
```

**IMPORTANT**  ⚠️ ⚠️ ⚠️ 

Some configurations have changed, You should change follow template file.

- [task-darwinia-ethereum.toml](https://github.com/darwinia-network/bridger/blob/1989d4d2d6bd97fd132c33248ed72b2ce0d9705d/.maintain/config/task-darwinia-ethereum.toml)
- [task-pangolin-ropsten](https://github.com/darwinia-network/bridger/blob/1989d4d2d6bd97fd132c33248ed72b2ce0d9705d/.maintain/config/task-darwinia-ethereum.toml)

In this version, some keys have been removed:

- [ethereum]
   - endpoint
   - subscribe_ring_address 
   - subscribe_kton_address 
   - subscribe_bank_address 
   - subscribe_bank_topics 
   - subscribe_issuing_address 
   - subscribe_issuing_topics 
   - subscribe_relay_topics 
   - subscribe_backing_address 
   - subscribe_backing_topics 
   - atom

And added these keys

- [task]
   - [interval_check](https://github.com/darwinia-network/bridger/blob/1989d4d2d6bd97fd132c33248ed72b2ce0d9705d/.maintain/config/task-darwinia-ethereum.toml#L44)
   - [check_timeout](https://github.com/darwinia-network/bridger/blob/1989d4d2d6bd97fd132c33248ed72b2ce0d9705d/.maintain/config/task-darwinia-ethereum.toml#L45)
- [thegraph]
   - [endpoint](https://github.com/darwinia-network/bridger/blob/1989d4d2d6bd97fd132c33248ed72b2ce0d9705d/.maintain/config/task-darwinia-ethereum.toml#L51)

**IMPORTANT**  ⚠️ ⚠️ ⚠️ 

All Ethereum contracts index start block [`13710000`](https://github.com/darwinia-network/bridger/pull/330/commits/9ff6b5e87d1788fdb74e8e6459ff0bb9bf589282), Please check your data, if the block height before the upgrade is less than this value, you need to check whether there are any missing events.

About more documents you can read
- [Darwinia-Ethereum Guide](https://github.com/darwinia-network/bridger/blob/1989d4d2d6bd97fd132c33248ed72b2ce0d9705d/task/task-darwinia-ethereum/docs/Guide.md)
- [Pangolin-Ropsten Guide](https://github.com/darwinia-network/bridger/blob/1989d4d2d6bd97fd132c33248ed72b2ce0d9705d/task/task-pangolin-ropsten/docs/Guide.md)

**Comment by HackFisher** [comment]
Found issues when I tried setup this in a brand new env, darwinia looks good, but ethereum keys do not work for me, I failed to initialize them and pop up the error logs in #443.
