### ISSUE TITLE
Refactor log

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/bridger#316]
We need to refactor log output to monitor bridger then send notify messages.
Some useful crates

- [tracing](https://crates.io/crates/tracing)
- [color-eyre](https://crates.io/crates/color-eyre)

**Comment by fewensa** [comment]
```
{"timestamp":"Dec 20 15:35:52.846","level":"TRACE","fields":{"message":"Set registry [Local]","metrics":true},"target":"bridger"}
```

**Comment by fewensa** [comment]
@furoxr Please remove fixed todo in source code
like this
https://github.com/darwinia-network/bridger/blob/f208f09699626b23a4a86bf045c1e2ee5f263925/bridges/pangolin-ropsten/bridge/src/service/redeem/mod.rs#L204

You can search using `todo: write log` keywords to find other todos

**Comment by furoxr** [comment]
Ok, I'll remove it in next pr

> @furoxr Please remove fixed todo in source code like this
> 
> https://github.com/darwinia-network/bridger/blob/f208f09699626b23a4a86bf045c1e2ee5f263925/bridges/pangolin-ropsten/bridge/src/service/redeem/mod.rs#L204
> 
> You can search using `todo: write log` keywords to find other todos
