### ISSUE TITLE
Moving start in config to cache db/file

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#32]
- [x] Move start to outside of config, this should not hardcoded in config and config is not for data store.
- [x] Provide a command for use to query/change the current ethereum scan start block.

**Comment by clearloop** [comment]
After #31, alone with reading config from toml with annotations.

**Comment by wuminzhe** [comment]
@clearloop create a new toml?

**Comment by clearloop** [comment]
> @clearloop create a new toml?

Better to use a rust mod like `default.rs` with only a static `toml` string.

```
pub static default: &str = r###""###;
```

Because the relative path `*.toml` is buggy.

**Comment by wuminzhe** [comment]
# read
if there is no cache file
    use default from code
else
    read from cache file
end

# write
if redeem all txs of a block successful 
    write the block to cache
end

**Comment by HackFisher** [comment]
Need to move scanned transactions to db together with start.

https://github.com/darwinia-network/bridger/blob/7ab4b90dd71af1bf69110cb23d8fb81458d73fb3/src/pool.rs#L53
