### ISSUE TITLE
Wrap schema for KV database to support cli command

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/bridger#377]
So, let'd do not have cli directly interact with db, and introduce a service between cli and db with key list and value type definitions. Then we can have the service properly handle this case.

_Originally posted by @HackFisher in https://github.com/darwinia-network/bridger/issues/343#issuecomment-989568744_

**Comment by HackFisher** [comment]
@fewensa Can we close this?

**Comment by fewensa** [comment]
Nope. @furoxr work on this issue
