### ISSUE TITLE
Vote guard is not working in v0.4.12?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#386]
https://darwinia.subscan.io/event?address=&module=ethereumrelay&event=all&startDate=&endDate=&startBlock=&endBlock=&timeType=date&version=1180

**Comment by HackFisher** [comment]
```
7f4f35648000-7f4f35649000 r--p 00025000 08:01 12997                      /lib/x86_64-linux-gnu/ld-2.23.so
7f4f35649000-7f4f3564a000 rw-p 00026000 08:01 12997                      /lib/x86_64-linux-gnu/ld-2.23.so
7f4f3564a000-7f4f3564b000 rw-p 00000000 00:00 0
7ffd18139000-7ffd1815a000 rw-p 00000000 00:00 0                          [stack]
7ffd181e1000-7ffd181e4000 r--p 00000000 00:00 0                          [vvar]
7ffd181e4000-7ffd181e6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
```

One of the bridger instance crashed, unfortunately it was running in screen, and not able to provide more logs.

**Comment by fewensa** [comment]
Maybe this issue is the same with #366 too many messages sent to the channel. have a known issue for guard service. 
#242
Please wait for @furoxr to fix this issue and  watch this issue
