### ISSUE TITLE
Upgrade guide for version v0.5.x

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/bridger#390]
A new version of bridger will be released soon, Please follow #364 We made a lot of changes, split each bridge to a single binary, the reason you can read #267 

If your current version is the latest 0.4.x please read #315 first, update your config file. then do some change to support 0.5.x

## Setps

1. Change your config filename
    Rename `task-` to `bridge-`
2. Set `BRIDGER_HOME` env if your config path not default path (~/.bridger).
3. Rename `database.kv` to `<bridge-name>.kv`. please see detailed description below.

### pangolin-pangoro / darwinia-crab

You can delete `auto_start` config

https://github.com/darwinia-network/bridger/blob/648ab20268c4f6ecb7f5459c7442988d7f4f7af8/.maintain/config/task-darwinia-crab.toml#L12-L15

### darwinia-ethereum

Some keys have been removed:

https://github.com/darwinia-network/bridger/blob/648ab20268c4f6ecb7f5459c7442988d7f4f7af8/.maintain/config/task-darwinia-ethereum.toml#L2
https://github.com/darwinia-network/bridger/blob/648ab20268c4f6ecb7f5459c7442988d7f4f7af8/.maintain/config/task-darwinia-ethereum.toml#L40

The encrypted private key has been removed in v0.5.x

⚠️ Please rename `database.kv` to `darwinia-ethereum.kv`. The reason you can see #407

### pangolin-pangoro / darwinia-crab

```bash
bridger pangolin-pangoro start
```

```bash
bridger darwinia-crab start
```

### pangolin-ropsten / darwinia-ethereum

```bash
bridger darwinia-ethereum start
```

```bash
bridger pangolin-ropsten start
```

## More

The more document you can read [Usage](https://github.com/darwinia-network/bridger/blob/d6b725a68f/docs/Useage.md)

| bridge | doc |
| -- | -- |
 | darwinia-ethereum | [Guide](https://github.com/darwinia-network/bridger/blob/d6b725a68f/bridges/darwinia-ethereum/docs/Guide.md) |
| pangolin-ropsten | [Guide](https://github.com/darwinia-network/bridger/blob/d6b725a68f/bridges/pangolin-ropsten/docs/Guide.md) |
| pangolin-pangoro | [Guide](https://github.com/darwinia-network/bridger/blob/d6b725a68f/bridges/pangolin-pangoro/docs/Guide.md) |
| darwinia-crab | [Guide](https://github.com/darwinia-network/bridger/blob/d6b725a68f/bridges/darwinia-crab/docs/Guide.md) |

**Comment by HackFisher** [comment]
I have no idea which version I'm running when start bridge tasks, github or local build?

All I have to deal with is bridger.sh right? But what's the `bridger` here?

> ```
> bridger pangolin-ropsten start
> ```

**Comment by HackFisher** [comment]
Default registry is github right? But which commit/branch/tag it is using?

```
% ./bridger.sh registry get
+++ dirname ./bridger.sh
++ cd .
++ pwd -P
+ BIN_PATH=/Users/denny/github.com/darwinia-network/bridger
+ cargo build --manifest-path /Users/denny/github.com/darwinia-network/bridger/frame/Cargo.toml --package darwinia-bridger
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
+ /Users/denny/github.com/darwinia-network/bridger/frame/target/debug/bridger registry get
TYPE: Github
PATH: https://github.com/darwinia-network/bridger
```

**Comment by fewensa** [comment]
## About bridger command

After merged and creating a new tag will be uplolad all binaries to Github release page. like this: https://github.com/fewensa/bridger/releases/tag/v0.5.0

![image](https://user-images.githubusercontent.com/37804932/148167948-f4f76bdb-113e-426c-b1f2-8025129124ab.png)

Then download the bridger package choose your os.

## About version

The bridger command will be read current bundle version

https://github.com/darwinia-network/bridger/blob/6c3076e52543fa8d42b636e913f09b91658db90d/frame/bin/src/external/provider/precompiled_binary.rs#L10
https://github.com/darwinia-network/bridger/blob/6c3076e52543fa8d42b636e913f09b91658db90d/frame/bin/src/external/provider/precompiled_binary.rs#L75

and download same version bridge from Github release page
