### ISSUE TITLE
Importing unnecessary crate hex

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/bridger#41]
## Desc

https://github.com/darwinia-network/bridger/blob/f3278469a57f84980be147f27ee806be3340c312/src/api/darwinia.rs#L83-L90

The `darwinia-bridge-primitives` crate already implemented the same function

https://github.com/darwinia-network/bridger/blob/f3278469a57f84980be147f27ee806be3340c312/primitives/src/byte.rs#L24-L39

**Comment by fewensa** [comment]
This issue can be close.
Now [bridger/src/api/darwinia.rs](https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/darwinia.rs) create Darwinia not have that code.

In commit [f327846](https://github.com/darwinia-network/bridger/commit/f3278469a57f84980be147f27ee806be3340c312), will return real `AccountId`. 

https://github.com/darwinia-network/bridger/blob/f3278469a57f84980be147f27ee806be3340c312/src/api/darwinia.rs#L82-L91

But now is in `DrawiniaSender` Struct.

https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/darwinia_sender.rs#L54-L68

and create this Struct is there

https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/darwinia.rs#L78-L89

not have this issue's problem.

**Comment by fewensa** [comment]
Wait, i saw these:

https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/darwinia_sender.rs#L86-L91

https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/darwinia/src/account.rs#L39-L44

https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/ethereum.rs#L152-L157

...

**Comment by songtianyi** [comment]
array_bytes TODO list

- [ ] remove darwinia common `primitives/array-bytes` crate, and replaced with external crate https://github.com/l2ust/array-bytes
- [ ] replace hex::decode and copy stuff with https://github.com/l2ust/array-bytes

please check this @AurevoirXavier @HackFisher

**Comment by AurevoirXavier** [comment]
`primitives/array-bytes` already been removed in https://github.com/darwinia-network/darwinia-common/pull/500

But there're still some other hex-type crates, please try to remove them.

**Comment by clearloop** [comment]
HEX TO DA MOOOON

**Comment by songtianyi** [comment]
```rust
use substrate_subxt::sp_core::bytes::to_hex
```
Does this need to be replaced too?

**Comment by AurevoirXavier** [comment]
Can you link that code here?

**Comment by songtianyi** [comment]
> Can you link that code here?

[import](https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/primitives/src/frame/bridge/relay_authorities.rs#L5)
[call](https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/primitives/src/frame/bridge/relay_authorities.rs#L122)

**Comment by xiaoch05** [comment]
> Wait, i saw these:
> 
> https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/darwinia_sender.rs#L86-L91
> 
> https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/darwinia/src/account.rs#L39-L44
> 
> https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/ethereum.rs#L152-L157
> 
> ...

`src/api/darwinia_sender.rs` and `bridger/src/api/darwinia.rs` are deprecated

**Comment by AurevoirXavier** [comment]
> > Wait, i saw these:
> > https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/darwinia_sender.rs#L86-L91
> > 
> > https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/darwinia/src/account.rs#L39-L44
> > 
> > https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/ethereum.rs#L152-L157
> > 
> > ...
> 
> `src/api/darwinia_sender.rs` and `bridger/src/api/darwinia.rs` are deprecated

These can be simply replaced with

```rust
hex2bytes_unchecked!(hex, length).into()
```

**Comment by songtianyi** [comment]
> > > Wait, i saw these:
> > > https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/darwinia_sender.rs#L86-L91
> > > 
> > > https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/darwinia/src/account.rs#L39-L44
> > > 
> > > https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/ethereum.rs#L152-L157
> > > 
> > > ...
> > 
> > 
> > `src/api/darwinia_sender.rs` and `bridger/src/api/darwinia.rs` are deprecated
> 
> These can be simply replaced with
> 
> https://docs.rs/array-bytes/1.1.0/array_bytes/macro.hex2array_unchecked.html
> 
> ```rust
> hex2bytes_unchecked!(hex, length).into()
> ```

`hex2bytes_unchecked` is `fn`  not `macro`

**Comment by songtianyi** [comment]
> > > > Wait, i saw these:
> > > > https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/darwinia_sender.rs#L86-L91
> > > > 
> > > > https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/darwinia/src/account.rs#L39-L44
> > > > 
> > > > https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/src/api/ethereum.rs#L152-L157
> > > > 
> > > > ...
> > > 
> > > 
> > > `src/api/darwinia_sender.rs` and `bridger/src/api/darwinia.rs` are deprecated
> > 
> > 
> > These can be simply replaced with
> > https://docs.rs/array-bytes/1.1.0/array_bytes/macro.hex2array_unchecked.html
> > ```rust
> > hex2bytes_unchecked!(hex, length).into()
> > ```
> 
> `hex2bytes_unchecked` is `fn` not `macro`
```rust
hex2array_unchecked!(hex, length).into()
```

**Comment by AurevoirXavier** [comment]
https://docs.rs/array-bytes/1.1.0/array_bytes/macro.hex2array_unchecked.html

**Comment by wuminzhe** [comment]
You need to remove `bridger/primitives/src/byte.rs`, it has a bug when your imported `Result`'s name is not `Result`.

**Comment by clearloop** [comment]
> You need to remove `bridger/primitives/src/byte.rs`, it has a bug when your imported `Result`'s name is not `Result`.

It's not a bug, it's a feature LOL

**Comment by songtianyi** [comment]
it's ok to remove byte macros in byte.rs
https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/primitives/src/byte.rs#L26

**Comment by songtianyi** [comment]
> it's ok to remove byte and hex macro in` byte.rs`?
> https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/primitives/src/byte.rs#L26
> 
> 
> https://github.com/darwinia-network/bridger/blob/21e1f76a90cee25fbbb6973a456432e499a7ba4a/primitives/src/byte.rs#L14

I will create another issue for this if necessary.
