### ISSUE TITLE
A Rococo mandatory header doesn't have Justifications

### ISSUE THREAD

**Issue by furoxr** [darwinia-network/bridger#478]
There is a Rococo mandatory header doesn't have Justifications, which stops the rococo subquery indexer. This issue will break off header relay from rococo to pangolin.

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/explorer/query/0x140706057cdf3fc16cb71c6993a361c47bb13b8d9ad63cd8cfab32e7c1dd52fb

**Comment by fewensa** [comment]
Rococo reseted
![image](https://user-images.githubusercontent.com/37804932/178145274-4809db26-f048-4e31-8033-e792190460c1.png)
