### ISSUE TITLE
Duplicate struct codes between primitives and darwinia-common

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#49]
A refactor is required to do later.

**Comment by clearloop** [comment]
If using the types of `darwinia-common`, `shadow`, `bridger` and `bridge-primitives` could not publish to crates.io anymore unless publishing `darwinia-common` to `crates.io` as well.

And the open-source software which will depend on `bridge-primitives` can not publish to `crates.io` either.

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/bridger/tree/master/primitives/src/chain

https://github.com/darwinia-network/darwinia-common/tree/master/primitives

This issue might be outdated since codes have changed a lot.

Could check further whether there are duplicate codes.

**Comment by songtianyi** [comment]
- [ ] EthereumHeader bridger/primitives/src/chain/ethereum/block.rs vs darwinia-common/primitives/ethereum-primitives/src/header.rs

**Comment by AurevoirXavier** [comment]
> Checklist for duplicate pub structs
> 
> * [ ]  EthereumHeader
> * [ ]  EthereumReceipt
> * [ ]  EthereumReceiptProof
> * [ ]  LogEntry
> * [ ]  RelayAffirmation<RelayHeaderParcel, Relayer, Balance, RelayHeaderId>
> * [ ]  RelayAffirmationId
> * [ ]  RelayVotingState

I draft some code here. https://github.com/darwinia-network/primitives/blob/main/relayer-game/src/lib.rs

**Comment by songtianyi** [comment]
> * EthereumHeader



> > Checklist for duplicate pub structs
> > 
> > * [ ]   EthereumHeader
> > * [ ]   EthereumReceipt
> > * [ ]   EthereumReceiptProof
> > * [ ]   LogEntry
> > * [ ]   RelayAffirmation<RelayHeaderParcel, Relayer, Balance, RelayHeaderId>
> > * [ ]   RelayAffirmationId
> > * [ ]   RelayVotingState
> 
> I draft some code here. https://github.com/darwinia-network/primitives/blob/main/relayer-game/src/lib.rs

why structs are separated into several dirs

**Comment by songtianyi** [comment]
> If using the types of `darwinia-common`, `shadow`, `bridger` and `bridge-primitives` could not publish to crates.io anymore unless publishing `darwinia-common` to `crates.io` as well.
> 
> And the open-source software which will depend on `bridge-primitives` can not publish to `crates.io` either.

Could we import them as submodules?

**Comment by HackFisher** [comment]
> > If using the types of `darwinia-common`, `shadow`, `bridger` and `bridge-primitives` could not publish to crates.io anymore unless publishing `darwinia-common` to `crates.io` as well.
> > And the open-source software which will depend on `bridge-primitives` can not publish to `crates.io` either.
> 
> Could we import them as submodules?

Submodule has no advantage over library dependency. (e.g. using git path)

I prefer using dependency as libraries, primitives being publish to crate.io is a plus, not required.

**Comment by HackFisher** [comment]
We have a lot of dependencies from substrate repo, does not have to separate them to other dirs IMO.

**Comment by clearloop** [comment]
> Could we import them as submodules?

This can be a solution, for example, you can refer to [git2](https://crates.io/crates/git2), which builds the C version `git2` as `git2-sys` and then publishes them to crates.io

**Comment by AurevoirXavier** [comment]
> > * EthereumHeader
> 
> > > Checklist for duplicate pub structs
> > > 
> > > * [ ]    EthereumHeader
> > > * [ ]    EthereumReceipt
> > > * [ ]    EthereumReceiptProof
> > > * [ ]    LogEntry
> > > * [ ]    RelayAffirmation<RelayHeaderParcel, Relayer, Balance, RelayHeaderId>
> > > * [ ]    RelayAffirmationId
> > > * [ ]    RelayVotingState
> > 
> > 
> > I draft some code here. https://github.com/darwinia-network/primitives/blob/main/relayer-game/src/lib.rs
> 
> why structs are separated into several dirs

Cause different usage.

Some of them require no std derive from `RuntimeDebug`, some require `Serialize`, `Encode`... So I decide to use features to manage this in https://github.com/darwinia-network/primitives.

**Comment by songtianyi** [comment]
trying to move briger/primitives/chain/etherum `LogEntry` to primitives repo

**Comment by songtianyi** [comment]
> trying to move briger/primitives/chain/etherum `LogEntry` to primitives repo

and its dependency `array.rs`
