### ISSUE TITLE
Flag to switch testnet or mainnet

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/bridger#60]
## Desc

Our contract addresses are rarely changed, it might be a choice to write it inside and switch by flag, for example `bridger run -v --testnet`

Or a switcher like the proxy config:

```
testnet = false;
```

**Comment by HackFisher** [comment]
Would like to keep it configurable for now, instead of hard code.

Since we provide sample conf files in .maintain folder, it would not be a problem for bridger.
