### ISSUE TITLE
Print the "invalid URI" if it cannot be parsed

### ISSUE THREAD

**Issue by wi1dcard** [darwinia-network/bridger#66]
![image](https://user-images.githubusercontent.com/25447002/97649063-52ffad80-1a91-11eb-9c43-652b951599bf.png)

It would be great if we can print out the value of "invalid URI", that helps while debugging or I'd have to look into the config file to find out where's the invalid character.

**Comment by songtianyi** [comment]
When this error happens you should open the config file to fix it, no difference between them.
What confused you may be that there are several URIs in there and you do not know which one is the URI that the program complained about

**Comment by wi1dcard** [comment]
> When this error happens you should open the config file to fix it, no difference between them.
> What confused you may be that there are several URIs in there and you do not know which one is the URI that the program complained about

Yes, you're correct. I was not able to figure out which one is invalid according to the error output.
