### ISSUE TITLE
No error log even bridger cannot connect to darwinia/eth nodes

### ISSUE THREAD

**Issue by wi1dcard** [darwinia-network/bridger#73]
For example, change the `rpc` in `[eth]` to a non-existent node address:

```
# ...
[eth]
rpc = 'https://mainnet.infura.ioabcd/v3/...'
start = 11149205
# ...
```

Bridger should report an error if it's not able to connect to the rpc endpoint. Please do not check the address ourselves, instead, it is better just throwing out the error from the HTTP client, as this is just an example case to let you easily reproduce the issue. We have tons of possibilities of different errors, like `connection refused` if the port is misconfigured, `no route to the host` if the IP is misconfigured, or `missing CA certificates` if we don't have `ca-certificates` installed, etc...

**Comment by AurevoirXavier** [comment]
No error log, on first connection.

**Comment by AurevoirXavier** [comment]
Not only the ethereum connection. Also the darwinia connection.
