### ISSUE TITLE
Client Error: Inner(Ws(Codec(ReservedOpCode)))

### ISSUE THREAD

**Issue by wi1dcard** [darwinia-network/bridger#76]
Part of the logs:

[darwinia-bridger-ws-codec-reserved-op-code.log](https://github.com/darwinia-network/bridger/files/5472242/darwinia-bridger-ws-codec-reserved-op-code.log)

The size of full logs is about 6 GiB, so I'd have to upload only a part of it. I believe those left logs contain no valuable info but only the error "Client Error: Inner(Ws(Codec(ReservedOpCode)))".

**Comment by wi1dcard** [comment]
Thought this could be closed since it might be fixed in jsonrpsee? @HackFisher

**Comment by HackFisher** [comment]
jsonrpsee is upgraded in #169 , closing this
