### ISSUE TITLE
[Darwinia Extrinsic Service]continuously send extrinsic could stop the service, better solution?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#83]
There were redeem examples, recent example is guard:

https://github.com/darwinia-network/bridger/commit/b8ff863b0e6ab8b349337befd54d9358492637f4

**Comment by HackFisher** [comment]
Another other better solution besides `tokio::time::delay_for(Duration::from_secs(6)).await`, if not, need to write document for this.

**Comment by fewensa** [comment]
This is the code before refactoring, but there is still this problem, merged into the same issue #242
