### ISSUE TITLE
ERROR darwinia_bridger::service::ethereum] Failed to get logs, due to `Transport error: hyper::Error(IncompleteMessage)`

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#87]

**Comment by wuminzhe** [comment]
Is this an occasional error? 
I found that when connecting to geth, there are occasional network problems.

**Comment by HackFisher** [comment]
> Is this an occasional error?
> I found that when connecting to geth, there are occasional network problems.

This is reproducible if we set start from very early block numbers
